import express from "express";
import cors from "cors";
import helmet from "helmet";
import { env } from "./config/env.js";
import { requireUser } from "./middleware/require-user.js";
import { projectsRouter } from "./api/projects.js";
import { geospatialRouter } from "./api/geospatial.js";
import { uploadsRouter } from "./api/uploads.js";
import { fail, ok } from "./utils/responses.js";
export const app=express();
app.disable("x-powered-by");app.use(helmet());app.use(cors({origin:env.FRONTEND_ORIGIN,credentials:true}));app.use(express.json({limit:"2mb"}));
app.get("/health",(_req,res)=>void ok(res,{status:"ok"}));
app.get("/ready",(_req,res)=>void ok(res,{status:"ready"}));
app.use("/api/v1",requireUser);app.use("/api/v1/projects",projectsRouter);app.use("/api/v1",geospatialRouter);app.use("/api/v1/assets",uploadsRouter);
app.use((_req,res)=>void fail(res,404,"NOT_FOUND","Route not found."));
if(process.env.VERCEL!=="1")app.listen(env.PORT,()=>console.log(`Project Atlas API listening on ${env.PORT}`));
export default app;
