alter table public.map_projects add column if not exists owner_id uuid references auth.users(id) on delete cascade;
alter table public.map_projects add column if not exists schema_version integer not null default 2;
alter table public.map_projects add column if not exists style_overrides jsonb not null default '{}'::jsonb;
alter table public.map_projects add column if not exists group_order jsonb not null default '["Trade Area Scan"]'::jsonb;
create table if not exists public.legacy_map_projects(id uuid primary key,payload jsonb not null,quarantined_at timestamptz not null default now());
insert into public.legacy_map_projects(id,payload) select id,to_jsonb(map_projects) from public.map_projects where owner_id is null on conflict(id) do nothing;
delete from public.map_projects where owner_id is null;
drop policy if exists "Allow public read access" on public.map_projects;
drop policy if exists "Allow public insert access" on public.map_projects;
drop policy if exists "Allow public update access" on public.map_projects;
drop policy if exists "Allow public delete access" on public.map_projects;
create policy "Owners read projects" on public.map_projects for select using(auth.uid()=owner_id);
create policy "Owners create projects" on public.map_projects for insert with check(auth.uid()=owner_id);
create policy "Owners update projects" on public.map_projects for update using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
create policy "Owners delete projects" on public.map_projects for delete using(auth.uid()=owner_id);
create index if not exists idx_map_projects_owner_updated on public.map_projects(owner_id,updated_at desc);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('atlas-assets','atlas-assets',false,10485760,array['image/png','image/jpeg','image/webp','image/svg+xml']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "Owners read atlas assets" on storage.objects for select using(bucket_id='atlas-assets' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "Owners upload atlas assets" on storage.objects for insert with check(bucket_id='atlas-assets' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "Owners update atlas assets" on storage.objects for update using(bucket_id='atlas-assets' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "Owners delete atlas assets" on storage.objects for delete using(bucket_id='atlas-assets' and (storage.foldername(name))[1]=auth.uid()::text);
revoke all on public.legacy_map_projects from anon,authenticated;
